spring:
  application:
    name: artway-storage-ms
server:
  port: 8089

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
