spring:
  application:
    name: artway-storage-ms
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 60000
  redis2:
    host: localhost
    port: 6379
    database: 2
    timeout: 60000
server:
  host: localhost
  port: 8089

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

artway:
  storage:
    cloud:
      dropbox:
        app_key: z9sz2i21nzfqdle
        app_secret: 6vos6gcy2qv4qpo
        redirect_uri: http://localhost:8089/api/auth/dropbox
      google-drive:
        client_id: 135842521742-ubu562041isbpdfilic6h91e2tl9q086.apps.googleusercontent.com
        client_secret: 39S0W8SmXdh6TLZa6ylq4hyT
      yandex-disk:
        client_id: 7a6ec505852b423aa959e76c748df472
        client_secret: ed179546687c4f8fa0664abde413eb88
        redirect_url: http://localhost:8089/api/auth/yandex

